usr/lib/udev/rules.d/64-bcachefs.rules
usr/lib/systemd/system/bcachefs-wait-devices@.service
usr/sbin/bcachefs
usr/sbin/fsck.bcachefs
usr/sbin/fsck.fuse.bcachefs
usr/sbin/mkfs.bcachefs
usr/sbin/mkfs.fuse.bcachefs
usr/sbin/mount.bcachefs
usr/sbin/mount.fuse.bcachefs
usr/share/man/man8/bcachefs.8
usr/share/bash-completion/completions/bcachefs
usr/share/initramfs-tools/hooks/bcachefs
signing/bcachefs-signing-ca.der usr/share/bcachefs-tools/
